# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1298a9a6cfa1bfaf9fe0c9f97032e70b7a02d2c7fcc3e1aaffca91be48b1865b946fe1bb5ef439bfa9242a9878f85903c000c8b58b07f852fa37c3c4b908669b

test:
  secret_key_base: 486b1c8400577f580cd52a4b4ea23902d6a1726a3229ad726731e56652993d5ef87fe8ba3812c0758d99926c0b76c5f4a5d576292035a9be309ba478d21ffb51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
